---
- name: Set Root Password
  become: true
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"

- name: Determine available groups
  getent:
    database: group

- name: Ensure user exists
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: |-
      {% for group in item.groups %}
      {% if group in ansible_facts.getent_group %}
      {{ group }}
      {% endif %}
      {% endfor %} | default( {{ item.name }} )
  loop: "{{ setup_users }}"

- name: Ensure that the user can sudo
  become: true
  ansible.builtin.template:
    src: sudoer.j2
    dest: '/etc/sudoers.d/{{ item }}'
    owner: root
    group: root
    mode: '0600'
  loop: "{{ sudo_users }}"
