---
- name: Set Root Password
  become: true
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"

- name: Ensure user exists
  become: true
  ansible.builtin.user:
    name: '{{ item.name }}'
    groups: '{{ item.name }},{{ item.groups }}'
  loop: "{{ setup_users }}"

- name: Ensure that the user can sudo
  become: true
  ansible.builtin.template:
    src: sudoer.j2
    dest: '/etc/sudoers.d/{{ item }}'
    owner: root
    group: root
    mode: '0600'
  loop: "{{ sudo_users }}"
