---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: localhost/extended-base-image:latest
  EE_BUILDER_IMAGE: localhost/extended-builder-image:latest
  PKGMGR_OPTS: '--nodocs --setopt install_weak_deps=0 --enablerepo=rhocp-4.10-for-rhel-8-x86_64-rpms'
dependencies:
  galaxy: requirements.yml
  system: bindep.txt
ansible_config: ansible.cfg

additional_build_steps:
 prepend:
    - COPY ansible.cfg /etc/ansible/ansible.cfg
