- name: Validate Required Certificate Parameters Provided
  ansible.builtin.assert:
    that:
      - root_ca_ssl_cert is defined
      - root_ca_ssl_cert | length > 0
      - aap_hub_ssl_key is defined
      - aap_hub_ssl_key | length > 0
      - aap_hub_ssl_cert is defined
      - aap_hub_ssl_cert | length > 0
      - aap_controller_ssl_cert is defined
      - aap_controller_ssl_cert | length > 0
      - aap_controller_ssl_key is defined
      - aap_controller_ssl_key | length > 0

- name: Setup Certificates
  ansible.builtin.include_tasks: manage-certificate.yml
  vars:
    certificate_file: "{{ certificate.variable }}"
    filename: "{{ certificate.filename }}"
    facts: "{{ certificate.facts }}"
  loop_control:
    loop_var: certificate
  loop:
    - {variable: "{{ root_ca_ssl_cert | default('') }}", filename: "{{ aap_certs_dir }}/root-ca.crt", facts: ["custom_ca_cert"]}
    - {variable: "{{ aap_hub_ssl_key | default('') }}", filename: "{{ aap_certs_dir }}/aap-hub.key", facts: ["automationhub_ssl_key"]}
    - {variable: "{{ aap_hub_ssl_cert | default('') }}", filename: "{{ aap_certs_dir }}/aap-hub.crt", facts: ["automationhub_ssl_cert"]}
    - {variable: "{{ aap_controller_ssl_cert | default('') }}", filename: "{{ aap_certs_dir }}/aap-controller.crt", facts: ["web_server_ssl_cert"]}
    - {variable: "{{ aap_controller_ssl_key | default('') }}", filename: "{{ aap_certs_dir }}/aap-controller.key", facts: ["web_server_ssl_key"]}
