---
- name: Configure ansible-pulling the content that applies to each host
  hosts: all
  vars_prompt:
  - name: vault_password
    prompt: What is the Ansible Vault password (needed to drop on the configured host)?
  roles:
  - osdu_lab.infra.bootstrap_pull
