---
- name: Update the authorized keys for the selected users
  ansible.posix.authorized_key:
    user: '{{ item }}'
    state: present
    exclusive: yes
    key: |-
      {% for desired_group in desired_groups %}
      {% for key in ssh_config_authorized_keys[desired_group] %}
      {{ key }}
      {% endfor %}
      {% endfor %}
  loop: '{{ ssh_config_users }}'
