---
- name: Ensure EPEL is enabled
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: Ensure fail2ban is installed
  ansible.builtin.dnf:
    name: fail2ban
    state: present
